# Generated by Django 5.2.4 on 2025-07-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_event_done_alter_event_created_at"),
    ]

    operations = [
        migrations.DeleteModel(name="CompletedEvent",),
    ]
